### ISSUE TITLE
Loading commute..

### ISSUE THREAD

**Issue by AzizOuedraogo88** [SamLewis0602/MMM-Traffic#10]
Hi SamLewis0602

First of all thank you for your work!!

I am a novice with all these stuff and i wanted to know witch kind of Google API key have you used??

Server, browser??
 
I am stuck and the message loading commute... and the request seems good on the google console.

Thanks!

**Comment by SamLewis0602** [comment]
Try typing this URL into your browser, replacing <api_key> with your actual api key:
```
https://maps.googleapis.com/maps/api/directions/json?origin=toledo%20ohio&destination=san%20antonio%20texas&key=%3Capi_key%3E
```

See if you get a successful response from that and let me know. This will help us figure out if the issue is with the API key or something with your config file.

**Comment by AzizOuedraogo88** [comment]
Hi have tried with your link and the key was not working!

I have created a new server key and i have removed the accents from my address (i am using french language) everything works find now.

Thank you!!

**Comment by SamLewis0602** [comment]
No problem! I'm glad it works! Let me know if you have any other questions or issues.
