### ISSUE TITLE
duration always 8 additional minutes  

### ISSUE THREAD

**Issue by josselynL** [SamLewis0602/MMM-Traffic#103]
Hi,

Thank you for this great module !
I'm under construction of my first MM, and i've a problem with your module.

The duration always have approximately 8 additionnal minutes, compare to google maps.

For example (fake route for the test) :

```javascript
{
                module: "MMM-Traffic",
                position: "bottom_left",
                config: {
                               accessToken: "pk.eyJ1XXX",
                               originCoords: "1.344786565363069, 43.52746634709673",
                               destinationCoords: "1.5599427085437545, 43.518527419180685",
                               firstLine: "{duration} mins",
                               secondLine: "duration test"
			}
}
```
[Google maps](https://www.google.fr/maps/dir/43.52746634709673,+1.344786565363069+/43.518527419180685,+1.5599427085437545/@43.5180656,1.3995847,17025m/data=!3m2!1e3!4b1!4m10!4m9!1m3!2m2!1d1.3447866!2d43.5274663!1m3!2m2!1d1.5599427!2d43.5185274!3e0) annnounce about 26 minutes to do this.

But, MMM-Traffic announce 34 min !

Its the same problem with my 2 real routes

Do you know why ?
Thank you and have a nice day.

edit : I have correctly inverted the longitude and latitude as shown in the readme. But it would be nice to make the sentence more visible because I was wrong at the beginning.

**Comment by SamLewis0602** [comment]
Hey there, MMM-Traffic uses Mapbox now instead of Google Maps. Will you compare what the module shows to mapbox travel time and see if they're similar?

**Comment by josselynL** [comment]
Hey Sam,
Thank you for your reply.

I've just compare information displayed on my MM and directly on mapbox.
MM display 26min, mapbox 27min, ok why not.

But, for exactly the same route, gmaps announce only 21min (and in reality it almost 19/20min).

i just think that mapbox is less precise for france and there is nothing you can do about it ... right ?

The difference is worst when there are traffic jams in the morning

Thank you :)

**Comment by SamLewis0602** [comment]
Ah yeah, it is possible that mapbox is less accurate. If the module is close to what you get on their site (settings could be slightly different between the two, leading to the 1 minute difference) then there's likely nothing else we can do. Apologies for the inconvenience!

There is actually a legacy branch of MMM-Traffic that has the last working Google Maps version. If you like, you can use that, just know that it will be unsupported (so I won't be able to commit time to helping with issues)
