### ISSUE TITLE
Cannot read property 'legs' of undefined

### ISSUE THREAD

**Issue by eazee187** [SamLewis0602/MMM-Traffic#12]
Hi there,

unfortunately I got an error using this module and it hangs with Loading commute...

The API-Key and stuff are correct, I get data using my config in a webbrowser.
I can see the "legs" section in the webbrowser, but I don't know why the module doesn't handle it.

Thanks in advance,
eazee187

**Comment by eazee187** [comment]
Hi ther,

update: Looks like it has something to do with the german umlauts ;-)
Will check a little further and give an update... ;-)

So nothing really wrong with your code...

**Comment by eazee187** [comment]
Hey,

just a problem with the german umlauts ä, ö ü.
Replaced the with ae, oe, ue and it works!

Thanks a lot for this great module!  :-)

**Comment by SamLewis0602** [comment]
Sorry for the delayed response, I'm glad you were able to get it working! No problem! :)
