### ISSUE TITLE
Module not displayed

### ISSUE THREAD

**Issue by RHeniz** [SamLewis0602/MMM-Traffic#14]
Hello SamLewis,

I am trying to get this module working and I am running into trouble. The magic mirror works and is displaying everything except the traffic module. I believe I installed everything right and I believe I am using the correct API key but the module will no display. any help would be appreciated. Thank you in advance.

**Comment by SamLewis0602** [comment]
Does the module show nothing at all, or does it show the loading message?

**Comment by RHeniz** [comment]
Nothing at all

**Comment by SamLewis0602** [comment]
Did you remember to add the module to your config as well as cloning it into your modules directory?

**Comment by RHeniz** [comment]
I added the module to the config.js file and followed your example. Withing my modules directory I have the MMM-traffic folder and within that folder I have the following:
-MMM-traffic.js
-node-helper.js
-node_modules
-package.json
-READ.md
-Traffic.css

**Comment by SamLewis0602** [comment]
Hm, that is strange, hard for me to know why nothing at all is showing up. Can you post your config here? I'd recommend replacing your personal info (address, api key) with X's before posting here.

**Comment by RHeniz** [comment]
Here is the conf file sorry for the format but at the moment I am just using putty to interface with the pi
[putty.zip](https://github.com/SamLewis0602/MMM-Traffic/files/313069/putty.zip)

**Comment by SamLewis0602** [comment]
No problem. Looks like you're using a hyphen instead of an underscore in `top_left`, fix that up and I would think that would solve the problem!

**Comment by RHeniz** [comment]
Thanks I got caught up looking at commas and brackets I didn't even think to look at that. Now I see the loading commute but it is stuck here. I checked my Google API key and I never received a request so I am guessing copied it wrong.

**Comment by RHeniz** [comment]
Sure enough that was it thanks for all your help and thank you for your quick response. Also I had a question. Is it possible to add multiple commutes?

**Comment by SamLewis0602** [comment]
No problem, I'm glad we were able to solve the problem! Yes, simply add another entry to your config to add a second commute. I'm currently using two on my mirror. You can use the same api key as well. I'm going to go ahead and close the issue, but feel free to post any other questions you have on this thread.
