### ISSUE TITLE
"classes" attribute has conflict with MMM-Facial Recognition Module

### ISSUE THREAD

**Issue by Jaghova** [SamLewis0602/MMM-Traffic#15]
Hi,

In your example config.js you are using an attribute called "classes"

```
module: 'MMM-Traffic',
    position: 'top_left',
    **classes: 'dimmed medium',** //optional, default is 'bright medium', only applies to commute info not route_name
    config: {
```

The same attribute name is use in MMM-Facial Recognition Module to call the user name that logs in.

If you try to use this module along with MMM-Traffic module there is a conflict that makes this module not work.

```
module: 'MMM-Traffic',
    position: 'top_left',
    **classes: 'default for_all',**
    **classes: 'dimmed medium',** //optional, default is 'bright medium', only applies to commute info not route_name
    config: {
```

This attribute should be named differently to avoid this conflict

**Comment by SamLewis0602** [comment]
The classes attribute is actually not part of the config object. In other
words, the name "classes" is not set by the creator of the module, it is
used by the MagicMirror. If you're having trouble using the module, feel
free to provide more information (stuck at loading message vs showing
nothing at all, etc) and I'd be happy to help you figure out what the issue
is.
