### ISSUE TITLE
Stuck on Loading Commute...

### ISSUE THREAD

**Issue by xer0design** [SamLewis0602/MMM-Traffic#16]
Hey!

For some reason the module is stuck on "Loading commute..." and when I check the maps api requests section it says it hasn't received any requests. Anyone have any idea what might be causing this and how to fix it? Thanks!

**Comment by SamLewis0602** [comment]
My first guess is that there may be an error with your API key. Try filling in your personal API key at the end of this URL and navigate to it in your browser. If it returns a json object with different information about the route then we'll know the API key is working correctly.

URL: `https://maps.googleapis.com/maps/api/directions/json?origin=texas&destination=new%20york&key=`

**Comment by xer0design** [comment]
API key was fine, in the end, I simplified the locations to just the town names rather than full long addresses and it started working! Thanks!

**Comment by SamLewis0602** [comment]
Hm, that's strange. It should work with whatever address you use since Google is pretty good at deciphering addresses. Try using your addresses at maps.google.com and see if it returns a result there. If so, then it should work on the module as well. If you want to figure out how to make your commute more accurate feel free to post and I'd be happy to help you out.

**Comment by dabnet795** [comment]
Hello I have tried the URL with my api key and am getting the following

{
   "error_message" : "This API project is not authorized to use this API.",
   "routes" : [],
   "status" : "REQUEST_DENIED"
}

Any thoughts?

**Comment by Jaydubya35** [comment]
> Hello I have tried the URL with my api key and am getting the following
> 
> {
> "error_message" : "This API project is not authorized to use this API.",
> "routes" : [],
> "status" : "REQUEST_DENIED"
> }
> 
> Any thoughts?

I had the same issue, you have to enable the Directions API. Go to APIs & Services > Library and search for Directions API and enable it.
