### ISSUE TITLE
Language settings do not work

### ISSUE THREAD

**Issue by mrpetermatyas** [SamLewis0602/MMM-Traffic#17]
Language cannot be set.

THX

**Comment by SamLewis0602** [comment]
The language settings only apply to the information received from the Google Maps API, i.e. the "56 mins" part. The prepended text, i.e. "Current commute is", must be changed manually using the `prependText` option in the config, as seen below.

|`prependText`|The text used in front of the commute time.<br><br>**Default value:** `'Current commute is'`|

**Comment by SamLewis0602** [comment]
If this solves your issue, please close it. Otherwise, feel free to ask any other questions and I'll help you solve the problem!

**Comment by mrpetermatyas** [comment]
Thank you!!

**Comment by SamLewis0602** [comment]
You're very welcome! Enjoy the module!
