### ISSUE TITLE
Module not working with origin/destination with special characters

### ISSUE THREAD

**Issue by derTim** [SamLewis0602/MMM-Traffic#19]
Thanks for this great module, did something similar for the old version of MagicMirror.

But it doesn't work with special characters (german umlauts) in the origin/destination address, 

What doesn't work:
```
origin: 'Werastraße 123, 70190 Stuttgart',
destination: 'Hans-Klemm-Straße 5, 71034 Böblingen',
```
The request in node_helper.js -> getCommute returns a 400 bad request.

Quick fix: URL Encode both addresses
```
origin: 'Werastra%C3%9Fe%20123%2C%2070190%20Stuttgart',
destination: 'Hans-Klemm-Stra%C3%9Fe%205%2C%2071034%20B%C3%B6blingen',
```

If I can figure this git stuff out i will implement a fix to the code and do a pull request :)

**Comment by SamLewis0602** [comment]
Ah, I never would have thought to test special characters. Thanks for doing that and good catch!

**Comment by Hellangel1987** [comment]
@derTim how can i Endcode the adresses ? i live in Nürnberg, same problem here...

**Comment by tommibaer** [comment]
Hi @Hellangel1987 

probiere es mal mit Nuernberg.
Ich wohne in der Straße Böttcherei.
Mit Boettcherei hat es funktioniert ;)

Gruß
tommibaer

**Comment by Hellangel1987** [comment]
@tommibaer thank your for your suggestion - i now only use City names instead of Street and City.
Now it Works with "Nuernberg" as Start and Destination "Muenchen" Thank you for that Hint :)

Regards
Sven

**Comment by SamLewis0602** [comment]
Hi everyone, I just tried the solution proposed above by @derTim and it appears to have worked. Please pull the latest version to your Pi and try using your specific addresses with the special characters and you should now be able to use the module as expected and get a commute time accurate to the minute. If you would, please return to this thread and let me know if it's working for you! Thanks all and enjoy.

**Comment by derTim** [comment]
I just tried the latest version, and it works great :) Thank you!

**Comment by SamLewis0602** [comment]
Glad to hear it! Thanks for the suggestion!
