### ISSUE TITLE
Commuting...

### ISSUE THREAD

**Issue by AgenceKN** [SamLewis0602/MMM-Traffic#20]
Hey, Nice module but I can't manage to make it work...
It keeps showing 'Commuting...' and nothing happens.
I just pasted your config settings and change API ID.
On the console, it says 'MMM-Traffic received a system notification: DOM_OBJECTS_CREATED'

Nothing seems to work. Did I do something wrong ?

**Comment by Pinktany** [comment]
Same issue here. API Key is working fine, but mirror shows only "Loading commute...".

**Comment by SamLewis0602** [comment]
Have you tested your api key in a browser to ensure that it is returning a valid response?

**Comment by AgenceKN** [comment]
Hello Sam. It works now... I think Google API Key takes a few minutes to be activated... I di not change anything since yesterday and now it works great!
Thanks man!

**Comment by SamLewis0602** [comment]
Glad to hear it! Enjoy.
