### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by ESOB86** [SamLewis0602/MMM-Traffic#23]
Traffic loads times on initialization but fails to update while Magic Mirror runs.

**Comment by SamLewis0602** [comment]
Hm, this behavior seems unlikely since subsequent updates are calling the same function that is called on initialization to update the traffic. Two questions:
1. Are you sure that the time for the commute you entered is actually changing?
2. What did you set as the value for `updateInterval`?

**Comment by ESOB86** [comment]
1.  I am sure the time is not changing, when I load the magic mirror in a web browser on a different PC it seems to force it to update.
2.  I set the interval to 120000.  

For more information I changed my checkout to the last update prior to August (7628f6c) and it returned to updating as expected.  I have not tried cycling through all the updates to find where it went from working to non-updating.  Prior to rolling back I actually reformatted my Raspbian image and started from scratch.

**Comment by SamLewis0602** [comment]
Looks like you're right, it's not updating. I recently accepted a pull request for the "arrive by" feature and it has caused several issues. I've learned a lesson about not thoroughly testing before accepting. I'll look into it, thanks for bringing it to my attention. If you have any programming experience and would like to help out I'd really appreciate it.

**Comment by ESOB86** [comment]
I can barely figure out how to do git commands.  I will stick to assembly and leave the coding to people like you.  Thanks for the awesome module and give me a heads up if you need me to change branches so you can test changes.

**Comment by SamLewis0602** [comment]
Go ahead and pull the latest update and see if it works. May have been a simple fix...I'm hoping that's it

**Comment by ESOB86** [comment]
One more question, how do I get back on the main branch?  (I am really bad at git)

**Comment by SamLewis0602** [comment]
To be honest, I'm not a git master either. Just delete the folder and reclone it 😝

**Comment by SamLewis0602** [comment]
I think it's working now, but I'm gonna leave this open until you confirm that your mirror is updating properly just to be safe. It's difficult to just look at it and know if it's updating or not since it's 9pm here so there's no traffic on my route and likely won't change until the morning. Please let me know whenever you're able to confirm that it's working or not!

**Comment by ESOB86** [comment]
I deleted everything and did a full new clone and after close to 18 hours it is working fine.  Thanks for your responsiveness.

**Comment by SamLewis0602** [comment]
Perfect! No problem, thanks for pointing out the issue.
