### ISSUE TITLE
Never finishes Loading

### ISSUE THREAD

**Issue by FIGHTINGHAWK81** [SamLewis0602/MMM-Traffic#24]
Having an issue that the module  never fully loads, I have the both the address input correctly in the config file. The Google API key is also there. It shows that the module is loading when the Mirror is launched, but never pulls up. I just continuously get Loading.... 
Please advise 
Thanks

**Comment by SamLewis0602** [comment]
Try testing your API key in your browser by adding it to the end of the URL in #16

**Comment by SamLewis0602** [comment]
Also, do you have any special characters in your address?

**Comment by SamLewis0602** [comment]
If you had special characters in your address, there was a bug that prevented these from working so you should be able to pull the latest version and it will work as expected. Thanks.
