### ISSUE TITLE
Missing departure_time parameter

### ISSUE THREAD

**Issue by nimasmi** [SamLewis0602/MMM-Traffic#26]
I get the response

``` json
{
   "error_message" : "Invalid request. Missing the 'departure_time' parameter.",
   "routes" : [],
   "status" : "INVALID_REQUEST"
}
```

Manually adding `&departure_time=now` in the browser URL fixed it for me. Should that key just be included in the `getParams` function at https://github.com/SamLewis0602/MMM-Traffic/blob/master/MMM-Traffic.js#L129?

**Comment by nimasmi** [comment]
I say 'fixed it for me', but I mean fixed the response when testing in a new tab in a normal browser. I'm still not getting past the 'loading commute' stage in electron.

I don't have a full grasp of what the code is supposed to do, but I don't see a pertinent request in the electron developer tools 'Network' tab, nor is `socketNotificationReceived` called.

**Comment by SamLewis0602** [comment]
Can you post your entry in config.js please? Feel free to remove the
addresses and api key first for privacy.

**Comment by nimasmi** [comment]
I take it back. I tried again today, and the module worked fine. I think it was related to it not being installed when I first started the node server.

**Comment by SamLewis0602** [comment]
Ah yep that'll do it. Glad you were able to figure it out. Enjoy the module!
