### ISSUE TITLE
Stuck Loading

### ISSUE THREAD

**Issue by andyipod1437** [SamLewis0602/MMM-Traffic#27]
Hey Thanks for the module. 
But i cannot seem to get it to work. I have tested the API with #16. I have also try  #10.  But the module still says stuck loading. Any ideas?
Thanks

**Comment by SamLewis0602** [comment]
Could you post your entry in config.js? You may want to replace personal info such as a home address or your api key.

**Comment by andyipod1437** [comment]
`		{ //MMM-Traffic
			module: 'MMM-Traffic',
			position: 'bottom_right',
			classes: 'dimmed medium', //optional, default is 'bright medium', only applies to commute info not route_name
			config: {
				api_key: 'API_KEY HERE',
				mode: 'driving',
				origin: 'Texas',
				destination: 'New York',
				route_name: 'Home to Work',
				changeColor: true,
				showGreen: false,
				limitYellow: 5, //Greater than 5% of journey time due to traffic
				limitRed: 20, //Greater than 20% of journey time due to traffic
				traffic_model: 'pessimistic',
				interval: 120000 //2 minutes
			}
		} ,`

Here is my config

**Comment by SamLewis0602** [comment]
Hm, nothing is jumping out at me. Do you see any errors in the console or on the server side logs?

**Comment by andyipod1437** [comment]
Thanks Sam for all your help.

It just took a long time. But It seems to working again.

**Comment by SamLewis0602** [comment]
Well I'm glad it's working! Feel free to reopen the issue if anything comes up again.

**Comment by andyipod1437** [comment]
Hey Sam. Sorry to bug you. But is there way i can put mutiple routes in?

**Comment by SamLewis0602** [comment]
No problem, not a bother! Yes, you can add a second entry in your config and it will render a separate module. You do not need to clone a second copy of the repository into your modules folder, just adding the second config entry will do the job!

**Comment by andyipod1437** [comment]
Thanks @SamLewis0602 That is what i found out after I ask. sorry

**Comment by SamLewis0602** [comment]
No problem, enjoy!

**Comment by fordpickup** [comment]
Sorry to resurrect this thread but I'm having the same "Loading Commute" problem, except mine didn't start working by simplifying the locations. I've tested the API and used a sample of working code from the forum. Do I need to do something in order to successfully reach Google services? 

Thanks for creation of this module, btw. I'm hoping this actually gets me to work on time by reminding me how much time it actually takes to get to work - it's not far but I can be a bit of a moron.

Code being used:
module: 'MMM-Traffic',
        position: 'bottom_right',
        classes: 'dimmed medium', //optional, default is 'bright medium', only applies to commute info not route_name
        config: {
            api_key: '<MY API KEY>',
            mode: 'driving',
            origin: 'Texas',
            destination: 'New York',
            route_name: 'Home to Work',
            changeColor: true,
            showGreen: false,
            limitYellow: 5, //Greater than 5% of journey time due to traffic
            limitRed: 20, //Greater than 20% of journey time due to traffic
            traffic_model: 'pessimistic',
            interval: 120000 //2 minutes

Original code that I was hoping to work:
 module: 'MMM-Traffic',
			    position: 'bottom_right',
			    classes: 'dimmed medium', //optional, default is 'bright medium', only applies to commute info not route_name
			    config: {
			        api_key: '<DAT API KEY>',
			        mode: 'driving',
			        origin: 'Saint Joseph, MI 49085',
			        destination: 'Benton Harbor, MI 49022',
			        arrival_time: '0815',
			        route_name: 'Home to Work',
				prependText: 'Current commute is',
			        changeColor: true,
			        showGreen: false,
			        limitYellow: 5, //Greater than 5% of journey time due to traffic
			        limitRed: 20, //Greater than 20% of journey time due to traffic
			        traffic_model: 'best_guess',
			        interval: 120000, //2 minutes
			        showWeekend: false,
				startHr: 7,
				endHr: 10,
			        allTime: false

**Comment by SamLewis0602** [comment]
No problem, I'm happy to help debug. So the rest of the modules on your mirror are working as expected?

**Comment by SamLewis0602** [comment]
I just took your exact config and pasted it into my own config.js with my own api key and it worked. So at this point I'd recommend checking your api_key again to make sure it works by visiting this link in your browser and pasting your api_key at the end:
https://maps.googleapis.com/maps/api/directions/json?origin=texas&destination=new%20york&key=

**Comment by SamLewis0602** [comment]
I just copied and pasted your config into my own config.js but used my own api_key and it worked on my mirror, so you may want to double check your config for typos. You can also look for errors in the web console in the browser, or logs from the node server itself. 

If you set up pm2 to run your mirror as mentioned in the MagicMirror documentation, then you can simply type `pm2 restart mm` but replace mm with whatever you named your process and you can see the logs.

**Comment by fordpickup** [comment]
I don't have the faintest clue why, but the code just all of a sudden works. I'm not sure if it was just using `pm2 restart mm` to restart but it just works now.

One other question is there a way to use `weekend: false` and/or `allTime: false` to completely hide the commute information? Or does that display dashes?

**Comment by fordpickup** [comment]
And thanks!

**Comment by fordpickup** [comment]
I take that back, now for some reason current weather and weather forecast aren't loading, even after reverting back to the previous code. I then went back and dropped the commute code back in and it didn't work until I restarted via pm2.

The other modules seem to be working fine (calendar and news feed). Sorry, I'm a bit new to Raspberry and I'm not quite sure how to go about fixing something like this.

**Comment by SamLewis0602** [comment]
Hm strange but if it works then it works, I suppose. The dashes are what display when there's no commute. The idea of that setting (which came from other contributor, not myself) was to avoid hitting the weekly request limit of the Google Maps API. Since the module wasn't being looked at overnight and some people only use it for work (weekends) it allows them to refresh the module more regularly during only the times they need it.

Having it display nothing should be relatively simple, let me look at it.

**Comment by SamLewis0602** [comment]
Okay it's done! Pull the latest version of the module by running a `git pull` inside the MMM-Traffic directory, and then check out the new `hideOffHours` config option in the README. Thanks for the idea!

**Comment by fordpickup** [comment]
Sam, you're friggin awesome! Thanks so much.

**Comment by MrMennens** [comment]
Can someone please tell me how to add the second address?

i'm stuck and keep trying new options... but none of them are working...
this is what i thought:

` {
                        "module": "MMM-Traffic",
                        "header": "Verkeersinformatie",
                        "position": "bottom_left",
                        "config": {
                 "api_key": "***",
                 "mode": "driving",
                 "origin": "***",
                 "destination": "***",
                 "arrival_time": "0815",
                 "route_name": "Route 1",
                "changeColor": true,
                "showGreen": false,
                "limitYellow": 5, //Greater than 5% of journey time due to traffic
                "limitRed": 20, //Greater than 20% of journey time due to traffic
                "traffic_model": 'pessimistic',
                "interval": 120000, //2 minutes
                "showWeekend": false,
                "allTime": true,
                "leaveByText": "Vertrek om",
                "arriveByText": "om aan te komen om"
        },
{
                 "api_key": "***",
                 "mode": "driving",
                 "origin": "***",
                 "destination": "***",
                 "arrival_time": "0815",
                 "route_name": "Route 2",
                 "changeColor": true,
                 "showGreen": false,
                 "limitYellow": 5,
                 "limitRed": 20,
                 "traffic_model": "pessimistic",
                 "interval": 120000,
                 "showWeekend": false,
                 "allTime": true,
                 "language": "nl",
                 "leaveByText": "Vertrek om",
                 "arriveByText": "om aan te komen om"
},
                        "classes": "dimmed medium"
                },

`

Can someone help me figuring out what i'm doing wrong?

**Comment by SamLewis0602** [comment]
Instead of having two configs inside of one module, actually add a second MMM-Traffic module.

**Comment by MrMennens** [comment]
Awesome, Will try that! 

(just thought of the same thing) 

Do I have to rename the module and copy the complete module folder? 

Or just add an extra module (same name) in the config?

**Comment by deder2** [comment]
Sorry to resurrect this thread but I'm having the same "Loading Commute" problem, except mine didn't start working by simplifying the locations. 

Do I need to do something in order to successfully reach Google services?



      {
         module: 'MMM-Traffic',
         position: 'top_left',
         classes: 'bright medium', //optional, default is 'bright medium', 
         config: {
            api_key: 'AIz*******************',
            mode: 'driving',
            origin: 'Paris, FR',
            destination: 'Créteil, FR',
            route_name: 'Travail',
            changeColor: true,
            showGreen: false,
            limitYellow: 5, //Greater than 5% of journey time due to traffic
            limitRed: 20, //Greater than 20% of journey time due to traffic
            traffic_model: 'best_guess',
            interval: 120000, //2 minutes
            loadingText: "Chargement...",
            prependText: "Monsieur :",
         }
      },


sorry for my english I'm french :)



TypeError: Cannot read property 'legs' of undefined
    at Request._callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_helper.js:31:45)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Whoops! There was an uncaught exception...





![img_20181011_155627](https://user-images.githubusercontent.com/44062045/46809242-5589f000-cd6e-11e8-8202-8ff0d0fa8ee5.jpg)

**Comment by SamLewis0602** [comment]
Did you test your API key using #16?
