### ISSUE TITLE
Use of Table

### ISSUE THREAD

**Issue by MichMich** [SamLewis0602/MMM-Traffic#3]
Is there any particular reason why you use a table in the wrapper? If this is converted to basic DIV's it can be used in the center elements as well.

**Comment by SamLewis0602** [comment]
My original thinking was to have the font awesome picture left-aligned and the commute text right-aligned, but I'll swap it over to spans inside a div instead.

**Comment by SamLewis0602** [comment]
Okay it's done. Had to change some CSS too to get it aligned correctly but it works.

**Comment by MichMich** [comment]
If you move to default divs, you don't need the `config.mainClass` solution. Since, this would now be possible using the default `classes` setting in the config.

**Comment by SamLewis0602** [comment]
Now the routeName's have changed to match the classes set in config.classes. Is there a way to keep those separate?

**Comment by MichMich** [comment]
If you set specific classes to that div. it should not be overwritten. Btw, I just use the regular title property for a module.

**Comment by SamLewis0602** [comment]
I'm not sure exactly how to use the default class. I'm assuming you're referring to `data.classes`, but how does the user set that in the config?

**Comment by SamLewis0602** [comment]
Ah never mind, I see that it's passed outside the `config {}` object.

**Comment by SamLewis0602** [comment]
Is there a way to default to `data.classes = 'bright medium'` if the user does not include it?

**Comment by SamLewis0602** [comment]
Figured it out, if no `classes` is given in the config then it defaults to the module name, in this case 'MMM-Traffic'. So a simple check for that in `start` makes sure the default classes are `'bright medium'`.

**Comment by MichMich** [comment]
The current method (probably using float?) gives an issue when there is a module below. Maybe add a clear float on the bottom of the module?

![screen shot 2016-04-21 at 09 43 25](https://cloud.githubusercontent.com/assets/210954/14701446/b582a736-07a5-11e6-8d41-28c1a914a584.png)

Also, would there be a way to just align everything to the left?

**Comment by SamLewis0602** [comment]
I currently have it set up with the symbol floated left and the commute info floated right, it looked neater to me. But I came across this same issue this morning, when my calendar increased in width there was just too big of a gap. Give me a couple hours and I'll remove the floats and just add a margin to the right of the symbol instead when I get back from class.

**Comment by SamLewis0602** [comment]
Okay it's done. It looks good to me. I also simplified the set up for the changeColor option that I added yesterday just for fun. Hope ya like it!

**Comment by MichMich** [comment]
Looks perfect! Thanks for the update!
Btw, @CFenner is working on a translation system, check out: https://github.com/MichMich/MagicMirror/issues/191
