### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by darrenelmslie** [SamLewis0602/MMM-Traffic#31]
Hi Sam,

Firstly, thanks for sharing such an awesome module - It's the first thing I added to my Magic Mirror and I love it!

This is more of a request than an issue - would it be possible to dynamically set the destination based on the day of the week (or even better, a holiday/non-holiday value)?  I suspect the latter would be incredibly difficult but perhaps the former might be a possibility?

I appreciate you've got your own life to live - if it's difficult to spare the time, woud you mind me raising the request and referencing the module on the Magic Mirror builders forum, to see if other developers are up for the challenge?

All the best,
Darren

**Comment by SamLewis0602** [comment]
You're very welcome! Hm, it's certainly an interesting idea. I think
setting it based on day of the week would certainly be possible, possibly
by using multiple objects within the config object. The tough part about
holidays is that days that are considered holidays can vary pretty widely
based on country, religion, etc. So it would be difficult to define in a
module what a "holiday" is.

Feel free to post anywhere else to try to find someone who's willing to do
it! I'm very busy at work right now so it'd be hard for me to work on the
first feature you mentioned. Anyone else's work on this module is greatly
appreciated! As long as it's thoroughly tested :P

**Comment by darrenelmslie** [comment]
Many thanks Sam :) 
You're right of course, regarding the holiday integration aspect. I suppose an iCAL feed could be used as a source but it starts to get quite complex quite quickly!

I'm wondering whether IanPerrin's MMM-ModuleScheduler could be employed as the go-between for this - it is designed to send notification/payloads to other modules based on a schedule.

If I set up a work/non-work schedule in it and have it push a notification to MMM-Traffic with the source/destination details as the payload. I think that might work? I'm just looking at the MMM-Traffic js trying to figure out how to do it but I'm struggling as I don't have much dev experience.. I'll keep trying though!

**Comment by SamLewis0602** [comment]
Hi Darren, I hope all is well with you. If you still use MagicMirror/MMM-Traffic, jchani added the ability to set different destinations for each weekday last April (I'm going through and cleaning up the issues 😄 ). Feel free to check it out if you haven't already!
