### ISSUE TITLE
Arrival time instead of commute time

### ISSUE THREAD

**Issue by doublevv** [SamLewis0602/MMM-Traffic#33]
Hi Sam,

Great module, very useful every morning!

I would have a feature request to make it even better :) : Is there a possibility to display the arrival hour instead of the time of commute? The way I would see that work is to take the current time and add it the commute time. Not sure how complex or possible that would be?

All the best,
Vincent

**Comment by SamLewis0602** [comment]
It seems like it would be relatively simple to implement, unfortunately I just don't have the time right now to get it done. If I find time I'll knock it out but otherwise feel free to work on it yourself and submit a pull request. I'm glad you enjoy the module!

**Comment by doublevv** [comment]
Thanks for the quick reply! Yes i wish to work on that myself, would you have any guidance on how to do it? I'm quite new with node/js :)

Thanks !

**Comment by SamLewis0602** [comment]
Sorry for the delay, life got busy! I would recommend checking out the module creation documentation in the MagicMirror project, it's done quite well. Pay particular attention to the socket notifications, as this is how `MMM-Traffic.js` and `node_helper.js` communicate with each other (as well as how all modules communicate between the client-side and server-side JS).

**Comment by doublevv** [comment]
Great tip, thanks for helping i'll give it a look!

Thanks again!

**Comment by rulemaker** [comment]
Hi 
I'm new to MagicMirror and had the same idea of using the arrival time. You just need to do some small adjustements to the code

**node_helper.js** Line 36
`self.sendSocketNotification('TRAFFIC_COMMUTE', {'commute':commute, 'url':api_url, 'trafficComparison': trafficComparison, 'summary':summary});`
to
`self.sendSocketNotification('TRAFFIC_COMMUTE', {'commute':commute, 'url':api_url, 'trafficComparison': trafficComparison, 'summary':summary, 'noTrafficValue':noTrafficValue, 'withTrafficValue':withTrafficValue});`

**MMM-Traffic.js**  
after getStyle() {} add
`    getScripts: function() {
        return ['moment.js'];
    },`

then check the getDom() function for
`trafficInfo.innerHTML = this.config.prependText + ' ' + this.commute;`

and change it to:
`
var end = moment().add(this.withTrafficValue,'seconds');
trafficInfo.innerHTML = this.config.prependText + ' ' + this.commute;
trafficInfo.innerHTML = trafficInfo.innerHTML + '<br/>Arrival at ' + end.format("H:mm");
`

This should do the Trick

**Comment by SamLewis0602** [comment]
Feel free to fork, test, and submit a pull request.
