### ISSUE TITLE
Arrival_time not working with transit or bicycling

### ISSUE THREAD

**Issue by doublevv** [SamLewis0602/MMM-Traffic#34]
Hi Sam,

It's me again.. I've noticed a bug with arrival time.

If the arrival_time has a value and mode is transit or bicycling, then commute keeps loading and nothing is displayed on the mirror ("TRAFFIC_TIMING" is not received in logs).

Any idea on how to correct that?

Thanks a lot,
Vincent

**Comment by SamLewis0602** [comment]
Interesting, thanks for bringing this to my attention. The arrival_time feature came from a pull request so let me take a look at it, will do so now.

**Comment by SamLewis0602** [comment]
I just pushed a change that I think should fix it, please pull the latest version, give it a try, and let me know if the fix worked! Thanks again for bringing this to my attention.

**Comment by SamLewis0602** [comment]
Closing this due to no response.
