### ISSUE TITLE
Multiple Commutes

### ISSUE THREAD

**Issue by Daimyo16** [SamLewis0602/MMM-Traffic#36]
First, I just wanted to say I love the module.

From a different thread I saw, you can have different routes display so I copied my first one and pasted the copy below it.  I edited the location to go to my girlfriend's work and changed her arrival_time (1230).  

Now it keeps flipping both modules back and forth between my departure time (6:39am) and her departure time (12:06pm).

Is there anything I can do so they don't both update to the same departure times?

**Comment by SamLewis0602** [comment]
Hi Daimyo16, sorry for the delay, I was enjoying American Thanksgiving with my family the past few days :D 
I have pushed a fix for this issue, please update to the latest version by running `git pull` in the MMM-Traffic directory and restart your mirror to pick up the changes. Thanks for pointing this out, and please let me know if you're still seeing the issue.

**Comment by Daimyo16** [comment]
Works like a champ! thanks for the quick turn around!!!

**Comment by SamLewis0602** [comment]
My pleasure! Enjoy the module!
