### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by mweth** [SamLewis0602/MMM-Traffic#37]
I am very new to using modules.  I followed the instructions to install the module.  I requested and received an API from Google, and I inserted the API into the script as instructed by the readme.  Even when using the example provided by the readme, the screen only says, "loading commute..."

Is there a way to debug this script to find where I am having an issue?

**Comment by SamLewis0602** [comment]
Hi mweth, sorry for the delay! 

The first thing I'd recommend you do is refer to #10 to see how you can test your API key.

For client-side errors, you can open the magicmirror app on your computer by opening a browser and typing in the IP address of your raspberry pi and the port of the magicmirror (likely 8888, so you would open xxx.xxx.xxx.xxx:8888 in your browser) and then opening the debug console in your browser.
