### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by paviro** [SamLewis0602/MMM-Traffic#4]
It would be awesome if you could work together with @MichMich so that the calendar may send a notification for all events that have a location and your module takes that notification and could then optionally display how long you need to get there and when you should start driving.

**Comment by MichMich** [comment]
Feel free to send a pull-request.

**Comment by paviro** [comment]
Will look into it if I find the time 🙂

**Comment by Cjkeenan** [comment]
Has there been any progress on this topic?

**Comment by MitchSS** [comment]
@Cjkeenan Check out - https://github.com/RedNax67/MMM-TrafficCal

**Comment by MichMich** [comment]
This feature is implemented in: https://github.com/MichMich/MagicMirror/commit/5858e862d95b8b1b4b248615d41559c338229dd8
