### ISSUE TITLE
Adding avoid tolls to the JS

### ISSUE THREAD

**Issue by montenegroja0405** [SamLewis0602/MMM-Traffic#41]
I have absolutely zero coding or java script or JSON knowledge and the fact that Ive gotten to where I am with this project in the time is amazing, But your module (which is amazing for my girlfriend who leaves late every day) takes the toll road which pretty much renders any accurate traffic patterns useless. On the google maps website (where you obtain the API key) it says to add avoid=tolls but with my knowledge, I simply dont know how or where to do so.

If you could possible take a look at that I would forever be grateful.

Thank you

Jose

**Comment by SamLewis0602** [comment]
I just pushed an update that adds this feature as an option in the config. It's untested as I'm about to board a plane but it was a simple change so I felt comfortable pushing it anyway. Please do a `git pull` in the MMM-Traffic directory to get the latest version, add `avoid:'tolls'` to your config, and come back to this thread and let me know if it is working for you!

**Comment by SamLewis0602** [comment]
Any updates?

**Comment by montenegroja0405** [comment]
Sorry I've veen side tracked and haven't worked on it. I'm not sure how to
git hub I'll have to read the installer again

**Comment by SamLewis0602** [comment]
No problem, I'd still love to hear your feedback! If you can log into your raspberry pi, use `cd path-to-your-magicmirror-folder/modules/MMM-Traffic` to get to the folder, then run `git pull` to get the latest version and restart your mirror to see the effect.
