### ISSUE TITLE
Red/Yellow/Green do not appear if arrival_time is specified

### ISSUE THREAD

**Issue by outjet** [SamLewis0602/MMM-Traffic#42]
I've noticed the "Leave by hh:mm" text will always stay the default color regardless of red/yellow limits. By removing the arrival_time parameter, the colors returned.

**Comment by SamLewis0602** [comment]
This has been fixed, thanks for pointing it out. Pull the latest version to have color affect your module when using arrival_time.

**Comment by djsunrise19** [comment]
Hi, I've acually the same problem. No color changes with the arrival_time. Do you have an idea / a fix?

**Comment by SamLewis0602** [comment]
Are you sure you're on the latest version?

**Comment by SamLewis0602** [comment]
You should also try removing the arrival_time parameter to see if the color changes either way. The same code is called to change the color regardless of whether the parameter is set, so if it changes one way then it should change the other as well.
