### ISSUE TITLE
Working fine then ... nothing

### ISSUE THREAD

**Issue by yomgdf** [SamLewis0602/MMM-Traffic#45]
Hello,

I'm very new to JS and MagicMirror so please forgive my candid question... just in case :)

I'm on a rpi 2 plateform with jessie. I installed the module yesterday, configured it via config.js file and everything was fine. A few hours later, i get back to my desk and see that the commute time wasn't displayed anymore.
Nothing change in the config file, I try to reload MagicMirror application, reboot the pi, look at the log (pm2 log mm) at startup... everything seems to be fine. 
My api key was created yesterday too. I can see activity on the google api dashboard and I can see when the activity stoped. I created a second one, same result.

The output on the screen is :
```
Current commute is --
Travail via --

```
Here is my config file :
```
                {
                        module: 'MMM-Traffic',
                        position: 'bottom_left',
                        classes: 'dimmed medium',
                        config: {
                                api_key: 'ABCDEFGH123',
                                mode: 'driving',
                                origin: '1 Boulevard Malesherbes, 75008 Paris',
                                destination: '1 Rue de Rivoli, 75004 Paris',
                                route_name: 'Travail',
                                changeColor: true,
                                showGreen: false,
                                limitYellow: 5,
                                limitRed: 20,
                                traffic_model: 'pessimistic',
                                interval: 60000,
                                showWeekend: false,
                                allTime: false
                        }
                },
```

Here are the logs of pm2 :
```
0|mm       | > magicmirror@2.1.0 start /home/pi/MagicMirror
0|mm       | > electron js/electron.js
0|mm       | Starting MagicMirror: v2.1.0
0|mm       | Loading config ...
0|mm       | Loading module helpers ...
0|mm       | No helper found for module: alert.
0|mm       | Initializing new module helper ...
0|mm       | No helper found for module: clock.
0|mm       | Initializing new module helper ...
0|mm       | No helper found for module: compliments.
0|mm       | Initializing new module helper ...
0|mm       | No helper found for module: currentweather.
0|mm       | No helper found for module: weatherforecast.
0|mm       | Initializing new module helper ...
0|mm       | All module helpers loaded.
0|mm       | Starting server op port 8080 ...
0|mm       | Server started ...
0|mm       | Connecting socket for: updatenotification
0|mm       | Connecting socket for: calendar
0|mm       | Starting node helper for: calendar
0|mm       | Connecting socket for: MMM-Traffic
0|mm       | MMM-Traffic helper started ...
0|mm       | Connecting socket for: newsfeed
0|mm       | Starting module: newsfeed
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.
0|mm       | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/abcdefg/basic.ics - Interval: 300000
0|mm       | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/abcdefg/basic.ics - Interval: 300000
0|mm       | Create new calendar fetcher for url: https://calendar.google.com/calendar/abcdefg/basic.ics - Interval: 300000
0|mm       | Create new news fetcher for url: http://www.bfmtv.com/rss/info/flux-rss/flux-toutes-les-actualites/ - Interval: 300000

```

Do you know anything about this "issu" ?
Is there a way to get logs from the module directly or something like debug mode to help understand what's go wrong ?

I can give further information if you ask.

**Comment by SamLewis0602** [comment]
Hi yomgdf. The reason you are seeing this behavior is because you have the "allTime" and "showWeekend" parameters set to false. If you check out the README you will see that these parameters basically disable the module during certain times to avoid hitting the limit that Google sets on their traffic APIs (It's a daily limit and you'll really only have to worry about reaching it if you have multiple clones of MMM-Traffic running at once). So, if you want the traffic to update all the time then you simply have to remove those two parameters and it will update 24/7. Thanks for using my module! I'd encourage you to read through the different config options in the README so you can customize it to your liking :)

**Comment by yomgdf** [comment]
So i read the README (!!!!!) and I try all the settings :)
Thank you very much !

Is there a way to hide the "entire module output" instead of just the "commute time" on hideOffHours ?

**Comment by SamLewis0602** [comment]
Yes, that's actually what hideOffHours does. It will completely hide the module when it's not during the days/times you specify.

**Comment by yomgdf** [comment]
That's what I understand but I can't make it disappear completly. 
Here is the output :
```
[icon]Temps de Trajet --
Travail via --
```

Here is my config :
```
                        module: 'MMM-Traffic',
                        position: 'bottom_left',
                        classes: 'dimmed medium', 
                        config: {
                                api_key: 'abcd',
                                mode: 'driving',
                                origin: '1 Boulevard Malesherbes, 75008 Paris',
                                destination: '1 Rue de Rivoli, 75004 Paris',
                                route_name: 'Travail',
                                loadingText: 'Chargement ...',
                                prependText: 'Temps de trajet',
                                changeColor: true,
                                showGreen: true,
                                limitYellow: 5,
                                limitRed: 20,
                                traffic_model: 'pessimistic',
                                interval: 60000,
                                showWeekend: false,
                                allTime: false,
                                startHr: 6,
                                endHr: 14,
                                hideOffHours: true
                        }

```

I read README twice again but i don't understand why module still appear.

**Comment by SamLewis0602** [comment]
Hm I'm not sure why that wouldn't work. I did just recently update the module with that feature so run `git pull` in the `MMM-Traffic` directory to make sure you have the latest version. Let me know if you already had the latest version and it still doesn't work after updating and restarting your mirror.

**Comment by SamLewis0602** [comment]
I actually may have just identified a bug with the hiding. I will test it tomorrow (approx. 12 hours from the time this comment was posted) and update it if necessary. I'll get back to you.

**Comment by SamLewis0602** [comment]
This has been fixed. Update your module and the hideOffHours parameter should take effect immediately. Thanks for pointing this out!

**Comment by yomgdf** [comment]
Yes !
Everything works nicely ! Thanks a lot for your time !

**Comment by SamLewis0602** [comment]
Awesome! No problem!
