### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by dmrowe84** [SamLewis0602/MMM-Traffic#46]
could someone take a look at my code to see what im missing? ever since i installed this mod the program wont recongize the config folder, theres gotta be an error in this mod code 

![2017-03-25-203802_1920x1080_scrot](https://cloud.githubusercontent.com/assets/26317586/24327634/b11ff21a-119b-11e7-8dc3-559c861b3bbd.png)

**Comment by SamLewis0602** [comment]
It is because you have a comma after the MMM-Traffic module section but it is the last module. If you remove that comma near the bottom it should work!

**Comment by SamLewis0602** [comment]
I'm going to close this because I'm pretty confident that's what it is but feel free to continue commenting if you have any other issues.

**Comment by dmrowe84** [comment]
i deleted the comma at the end of the page and i still get the same response :(

![2017-03-25-223923_1920x1080_scrot](https://cloud.githubusercontent.com/assets/26317586/24328344/d6025652-11ac-11e7-8d82-f1087bbcb89a.png)

![2017-03-25-224318_1920x1080_scrot](https://cloud.githubusercontent.com/assets/26317586/24328345/e00d0aac-11ac-11e7-8b56-63d38d5fb393.png)

![2017-03-25-224327_1920x1080_scrot](https://cloud.githubusercontent.com/assets/26317586/24328350/e82c0ab2-11ac-11e7-8e2a-26d62f63aaf1.png)

**Comment by SamLewis0602** [comment]
And deleting the MMM-Traffic config makes it work again?

**Comment by dmrowe84** [comment]
Yes, I thought I put everything in the right way. I just installed it a few days ago so it shouldn't be out of date

**Comment by SamLewis0602** [comment]
Oh I think I got it! Look at the single quotes in the route_name parameter, they are slightly angled compared to the single quotes in the leaveByText parameter. Some text editors have stylized quotes that mess with code and cause hair-pulling syntax errors :) so check all of the single quotes in the MMM-Traffic config and make sure they look straight up and down and not stylized. If you can't get your editor to type regular single quotes, you should be able to copy one of the "correct" single quotes and paste it over the stylized ones. Let me know if this works!

**Comment by dmrowe84** [comment]
That did work! Thank you so much! :):)
However after I start up MM I get just a black screen, I'm assuming it's trying to load? It been blank for about 5 mins now

**Comment by SamLewis0602** [comment]
Hm it definitely shouldn't take that long. Do you see any errors in the terminal when you start it?

**Comment by dmrowe84** [comment]
No, it loaded up perfectly

**Comment by dmrowe84** [comment]
So I found this closed issue created by @bikerboymohit 
Oh, thank you for deleting that comment. So I fixed the issue. When I installed it initially I have installed in under /modules/defaults/ directory. I then removed the file and installed it under /modules directory and ola! it worked.
Not to bug you more on this. But I was wondering that a map would be shown in the background. Does it? Or is there any other module which actually does that?

Thank you for the prompt responses

If I give this a shot do I need to uninstall the mod or cam I just move the file to /modules/directory?

**Comment by SamLewis0602** [comment]
Ahhh yes, you definitely have to have it in the MagicMirror/modules directory. Just delete the current MMM-Traffic directory you have using `rm -r path_to_MMM-Traffic` and then run a git clone the same way you did before except make sure that it is installed in the modules directory.

**Comment by dmrowe84** [comment]
Ok, thank you for your time and patience! I'll update tonight when I get home from work! 
Thanks again!

**Comment by SamLewis0602** [comment]
No problem!

**Comment by dmrowe84** [comment]
Just want to clarify before I mess something up, to get to the home folder I input: 
cd $HOME/MagicMirror 

To get to the module folder it would be the same just add /modules to the end of the line?
cd  $HOME/MagicMirror/modules

**Comment by SamLewis0602** [comment]
That's correct

**Comment by dmrowe84** [comment]
I want to let you know, I got everything to work perfectly! With your help of course! 
That you for this great mod and your patience! :)

**Comment by SamLewis0602** [comment]
That's great, I'm glad to hear it! Feel free to let me know if you run into any more issues, and enjoy the module!
