### ISSUE TITLE
Not showing Module with hideOffHours: true

### ISSUE THREAD

**Issue by wilburforce83** [SamLewis0602/MMM-Traffic#47]
Hi, this is an awesome module, but I am having an issue with using the hideHoursOff argument:

`{
    module: 'MMM-Traffic',
    position: 'top_left',
classes: 'bright medium', //optional, default is 'bright medium', only applies t$
    config: {
        api_key: '***********************************',
        mode: 'driving',
        origin: '**************************',
        destination: '************************',
        arrival_time: '0930',
        route_name: 'Home to Work',
        changeColor: true,
        showGreen: false,
        limitYellow: 5, //Greater than 5% of journey time due to traffic
        limitRed: 20, //Greater than 20% of journey time due to traffic
        traffic_model: 'pessimistic',
        interval: 120000, //2 minutes
        showWeekend: false,
        allTime: false,
        startHr: 6,
        endHr: 12,
        hideOffHours: true
    }
},

{
    module: 'MMM-Traffic',
    position: 'top_left',
    classes: 'bright medium', //optional, default is 'bright medium', only applies t$
    config: {
        api_key: '******************************',
        mode: 'driving',
        origin: '***************',
        destination: '********************',
        arrival_time: '1845', //optional, but needs to be in 24 hour time if used.
        route_name: 'Work to Home',
        changeColor: true,
        showGreen: false,
        limitYellow: 5, //Greater than 5% of journey time due to traffic
        limitRed: 20, //Greater than 20% of journey time due to traffic
        traffic_model: 'pessimistic',
        interval: 120000, //2 minutes
        showWeekend: false,
        allTime: false,
        startHr: 15,
        endHr: 20,
        hideOffHours: true
    }
},
`

I believe I am using it correctly, I am expecting it to show the first travel time in the morning and the second in the afternoon, and for it not to be there during the other times outside startHr, and endHr, but it is just not showing at all.

As soon as I put hieOffHours: false, it shows both all the time, am I putting the start and end arguments incorrectly?

Many thanks!!!

Will

**Comment by wilburforce83** [comment]
Ah, I think this is caused by a conflict of having two commutes listed; when commute 1 is outside the designated hours 'hideOffHours: true' tags both to hide. When the commute 2 is outside the designated hours it is hiding both too, meaning that the module is never shown. I guess I will have to choose a single commute if I want it to only show during certain hours. 

Please could you tag this a feature request instead of an issue. Many thanks!

**Comment by SamLewis0602** [comment]
That's strange, I haven't seen that behavior when I have two commutes active. I will look into it when I get back, but one thing that would cause this behavior is if the parameters are exactly the same for both commutes. Because the way it differentiates between commutes is using the URL that's sent to Google Maps

**Comment by SamLewis0602** [comment]
I tried several different combinations but I can't reproduce this issue. Can you verify that you have the latest version of the module and your origin and destination parameters are not the same for both commutes?

**Comment by wilburforce83** [comment]
Ah, okay. So basically the second commute is the first one in reverse.  I think this is my problem.  I'll change the address for the second commute so that it is a slightly different pair of addresses and test. Thank you so much for your help - I will get back with the results soon!

**Comment by SamLewis0602** [comment]
Even the same exact addresses should work as long as their positions are switched for the two different commutes. Weird. Make sure you're on the latest version though and if you're still having issues I can help you out tomorrow.

**Comment by wilburforce83** [comment]
Hi Sam, thank you for all your help! I am not sure what is the root cause, but I have resolved my issue, and now have my commute to, and from work coming up at the correct times. What I needed to do was to remove the "arrival_time" variable from both module configs -- this actually worked better for me anyway as it gives a live commute time at the point of leaving, and on the way home gives my wife an idea of the traffic delays on my way home. I am not sure why it was causing a problem, but my guess would be the time format differences between startHr/endHr (0-23) and arrival_time (0000-2359).

Thanks, I hope this also helps anyone else that has come across this :D Cheers!!

**Comment by SamLewis0602** [comment]
Man that's so strange, last night I tested by having 4 different commutes up, two using arrival time with one of the arrival time ones hidden and it only hid one while the other arrival time stayed up.
Either way, since you prefer the commute time style anyway, at least it's working as expected for you that way. Enjoy the module!

**Comment by wilburforce83** [comment]
Haha, yeah that is really odd! I'm all up to date etc. Hey ho! It's working perfectly for me now with the commute time instead of arrival time, so I'm happy. It's an awesome module, thanks for your work on it!

**Comment by SamLewis0602** [comment]
My pleasure!
