### ISSUE TITLE
commute is never displayed, if hideOffHours: true

### ISSUE THREAD

**Issue by MrXfree11** [SamLewis0602/MMM-Traffic#49]
Hi, i really can't find my mistake. If i set the hideOffHours: true the commute time is never displayed. Any chance someone could point me into the right direction?

settings from config.js
{	module: 'MMM-Traffic',
	position: 'top_left',
	classes: 'dimmed medium', //optional, default is 'bright medium', only applies to commute info not route_name
	config: {
		api_key: '*****************************',
		mode: 'driving',
		avoid: 'highways',
		origin: 'Marktplatz 1, 70173, Stuttgart',
		destination: 'Kaesbruennlestraße, 71063, Sindelfingen',
		arrival_time: '1630', //optional, but needs to be in 24 hour time if used.
		route_name: 'Stuggi->SiFi',
		changeColor: true,
		showGreen: false,
		limitYellow: 5, //Greater than 5% of journey time due to traffic
		limitRed: 20, //Greater than 20% of journey time due to traffic
		traffic_model: 'pessimistic',
		interval: 120000, //2 minutes
		showWeekend: false,
		allTime: false,
        	hideOffHours: false
	}
},

i also checked the values in the MMM-Traffic.js file, they're untouched 
        startHr: 7,
        endHr: 22,
now it's 14:42 in my timezone, this should be within the range of 7 to 22 arrival is set to 1630 but if i change hideOffHours from false to true the module disappears.

**Comment by SamLewis0602** [comment]
When you can see the commute does it show a valid 'leave by' time?

**Comment by MrXfree11** [comment]
Hey, thanks for the fast reply.
if hideOffHours set to false, it shows a vaild Leave by time an Street recommendation e.g. Summary

**Comment by SamLewis0602** [comment]
Cool, just wanted to make sure the api_key and other settings were working. Do you know how to look at the server-side logs? If you're using pm2 as described in the MagicMirror set up then you can type `pm2 logs mm`

**Comment by MrXfree11** [comment]
yes, i sticked as close as possible to the manual. 
this is what i got from the log streaming..

pi@MagicMirror:~ $ pm2 logs mm
[TAILING] Tailing last 15 lines for [mm] process (change the value with --lines option)
/home/pi/.pm2/logs/mm-error-0.log last 15 lines:
0|mm       | npm ERR!
0|mm       | npm ERR! Failed at the magicmirror@2.1.1 start script 'sh run-start.sh'.
0|mm       | npm ERR! Make sure you have the latest version of node.js and npm installed.
0|mm       | npm ERR! If you do, this is most likely a problem with the magicmirror package,
0|mm       | npm ERR! not with npm itself.
0|mm       | npm ERR! Tell the author that this fails on your system:
0|mm       | npm ERR!     sh run-start.sh
0|mm       | npm ERR! You can get information on how to open an issue for this project with:
0|mm       | npm ERR!     npm bugs magicmirror
0|mm       | npm ERR! Or if that isn't available, you can get their info via:
0|mm       | npm ERR!     npm owner ls magicmirror
0|mm       | npm ERR! There is likely additional logging output above.
0|mm       |
0|mm       | npm ERR! Please include the following file with any support request:
0|mm       | npm ERR!     /home/pi/MagicMirror/npm-debug.log

/home/pi/.pm2/logs/mm-out-0.log last 15 lines:
0|mm       | Starting server on port 8080 ...
0|mm       | Starting server op port 8080 ...
0|mm       | You're using a full whitelist configuration to allow for all IPs
0|mm       | Server started ...
0|mm       | Connecting socket for: updatenotification
0|mm       | Connecting socket for: calendar
0|mm       | Starting node helper for: calendar
0|mm       | Connecting socket for: newsfeed
0|mm       | Starting module: newsfeed
0|mm       | Connecting socket for: MMM-Traffic
0|mm       | MMM-Traffic helper started ...
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.
0|mm       | Create new calendar fetcher for url: http://www.calendarlabs.com/templates/ical/US-Holidays.ics - Interval: 300000
0|mm       | Create new news fetcher for url: http://www.faz.net/rss/aktuell/ - Interval: 300000

[STREAMING] Now streaming realtime logs for [mm] process

**Comment by SamLewis0602** [comment]
Hm I don't see any issues there. It's 9:40am here so I won't be able to dig into this until later today after work, but as of right now I'm not sure why that would be happening.

**Comment by MrXfree11** [comment]
yes sure take your time, appreciate your support.

**Comment by SamLewis0602** [comment]
Hey MrXfree11, I'm really sorry for the delay on this. I just pushed a fix for this issue, so pull down the latest version and you should be able to use hideOffHours as expected. Thanks for pointing this out! Sorry again for the delay!

**Comment by SamLewis0602** [comment]
Going to go ahead and close this.
