### ISSUE TITLE
Stuck in loading.

### ISSUE THREAD

**Issue by janarta** [SamLewis0602/MMM-Traffic#50]
Hi Sam,

Thx for creating this module! I have tought one question, im still stuck in loading face. The api key works fine when tested (lots of links, also the ones mentioned earlyer #25) When put in browser it show up the request in mu developer console.

Have tried with different requests and with place id:s. Also have pulled the latest update. 

Tryed to figure this out but now im headbanging the wall :D

**Comment by SamLewis0602** [comment]
Hi Janarta, could you post your config? You can remove personal info like address and api key.

**Comment by janarta** [comment]
Hi,

{
      module: "MMM-Traffic",
      position: "bottom_bar",
      classes: "dimmed medium",
      config: {
        api_key: "https://maps.googleapis.com/maps/api/directions/json?origin=place_id:",
        mode: "driving",
        origin: "",
        destination: "",
        //arrival_time: "0900",
        route_name: "",
        changeColor: "true",
        showGreen: "true",
        limitYellow: 15,
        limitRed: 30,
        traffic_model: "pessimistic",
        interval: 120000,
        showWeekend: false,
        allTime: false,
      },
    }, {
      module: "MMM-Traffic",
      position: "bottom_bar",
      classes: "dimmed medium",
      config: {
        api_key: "https://maps.googleapis.com/maps/api/directions/json?origin=place_id:",
        mode: "driving",
        origin: "",
        destination: "",
        //arrival_time: "0815",
        route_name: "",
        changeColor: "true",
        showGreen: "true",
        limitYellow: 15,
        limitRed: 30,
        traffic_model: "pessimistic",
        interval: 120000,
        showWeekend: false,
        allTime: true,
      },
    },

I have tryed with different modes, intervals, with arrival time, showwekend, alltime and different google api:is. And it shows everything fine with this api call when put in browser. For some reason it wont do it from the mm..

**Comment by SamLewis0602** [comment]
Is that URL the value you're using for your api key?

**Comment by janarta** [comment]
yes, its like this (without place id:s and api, they are correct) https://maps.googleapis.com/maps/api/directions/json?origin=place_id:*****&destination=place_id:*****&*****

**Comment by SamLewis0602** [comment]
So, that's not the correct value for the api key. The module will take care of building the URL for you. The api key is a value like this: aSyBEawdDQyQ2qu_EWlZV-1fExwCtMecSw0A

**Comment by janarta** [comment]
yea i did, i will try with only the api key there

**Comment by SamLewis0602** [comment]
Yes give that a try and let me know if it works.

**Comment by janarta** [comment]
Darn mate! You did this to easy :) Thank you alot, now it works!!

**Comment by SamLewis0602** [comment]
No problem, glad I could help! Enjoy the module!
