### ISSUE TITLE
Calculated time and track from module differs to Google Maps results

### ISSUE THREAD

**Issue by DrDenz** [SamLewis0602/MMM-Traffic#51]
While setting up MMM-Traffic told me that my way to work will be around 1 hour 52 min and the summary says via 2 highways, quite far away from normal track.

I used the example URL from Google with my locations to check the results. There the track and the estimated time are matching real life.

https://maps.googleapis.com/maps/api/directions/json?origin=75+9th+Ave+New+York,+NY&destination=MetLife+Stadium+1+MetLife+Stadium+Dr+East+Rutherford,+NJ+07073&key=YOUR_API_KEY

**Comment by DrDenz** [comment]
Okay, solved it by myself :)

According to Google´s example I edited the config like this

origin: 'Street+Number+Postcode+City',
destination: 'Street+Number+Postcode+City',

now I get the right estimation and the right track

**Comment by SamLewis0602** [comment]
I guess it was just something weird with how Google parsed the address. Glad you got it to work! Thanks for the info!
