### ISSUE TITLE
New Update 

### ISSUE THREAD

**Issue by dmrowe84** [SamLewis0602/MMM-Traffic#52]
To get this new commit Update, can I just pull the code and type it into my .js file or do I have to flash an update install?

**Comment by SamLewis0602** [comment]
You can just navigate into your `MMM-Traffic` directory and run `git pull` and then you will have the latest version. You'll have to restart your mirror for it to pick up the code changes.

**Comment by dmrowe84** [comment]
Thank you! 😁

**Comment by SamLewis0602** [comment]
No problem.
