### ISSUE TITLE
Multiple Destinations REQUEST

### ISSUE THREAD

**Issue by lcowan94** [SamLewis0602/MMM-Traffic#53]
Hello,
I think it would be a good option to be able to have multiple destinations, eg. Work, Uni, School, etc.
Do you think this is something possible to add?
Thanks
Luke

**Comment by SamLewis0602** [comment]
You can actually do this now. If you just add a second and completely separate config object in your config.js, you can have multiple copies of the module running. Give it a try and let me know if you run into any issues.

**Comment by lcowan94** [comment]
Works fine. Thank you
