### ISSUE TITLE
named day specific destinations not loading

### ISSUE THREAD

**Issue by emilyj0y** [SamLewis0602/MMM-Traffic#55]
Hi, 
I'm able to get my general destination working, but am unable to implement the specific weekday destinations (mon_destination, tues_destination, etc). When I tried it as in the example code, none of the weekdays showed up, only my main 'destination'. I tried running the module twice in my config.js, as I found elsewhere that's how to get two destinations going--if I only have the mon_destination named in the second instance, that module shows as loading and never changes. If I put in a different destination into the second module's 'destination' field, it works. 

How do I get the daily destinations to work? Am I supposed to be able to run them in the same instance of the module as my standard work destination?

**Comment by SamLewis0602** [comment]
@jchani can you speak into this issue? I'm not intimately familiar with the weekday destinations code.

**Comment by SamLewis0602** [comment]
emily, I haven't been able to reproduce this issue. If you are still seeing the issue, please update your module to the latest version and see if it still isn't working right. If so, reopen this issue and I'll work with you to get it fixed.
