### ISSUE TITLE
Multiple mode

### ISSUE THREAD

**Issue by lunaticasylum** [SamLewis0602/MMM-Traffic#56]
Hi Sam,

First, I would like  to congratulate you for the job you have done done!!! 

I was wondering if it is possible to have more than one mode in the same module to get to the same adress ? 

I managed to have driving mode and transit mode but in two different modules and not in only one. 

Thanks for you help

Yann

**Comment by SamLewis0602** [comment]
Currently, you would have to add two modules to use the different modes as you've already done. I will mark this as an enhancement and if anyone is able to take a stab I can look at pull requests.

**Comment by lunaticasylum** [comment]
Thanks for your answer Sam. 

Have a nice day

Yann
