### ISSUE TITLE
Adding line break in prependText

### ISSUE THREAD

**Issue by Raddy13** [SamLewis0602/MMM-Traffic#57]
Is there a way to add a line break to the prependText? I have two modules to two different destinations, so I have the prependText set up to say "Current commute time to Destination A is" and "Current commute time to destination B is". Unfortunately, it's extending halfway across the screen and overlapping with the center text.

I tried setting it up as:
`prependText: 'Travel time to\nDestination A is',`
But it still shows up as a single line. Any ideas?

**Comment by SamLewis0602** [comment]
Hi Raddy, sorry for the delay. I'm not sure if this will work, but you could try using <br> as a line break in your config since that text is just being inserted into the HTML. Let me know if that works, if not I can try to figure something else out.

**Comment by SamLewis0602** [comment]
Hey, did using `<br>` end up working?

**Comment by SamLewis0602** [comment]
For future readers, using `<br>` in any textual config option will insert a line break.
