### ISSUE TITLE
Display request

### ISSUE THREAD

**Issue by crazyanageek** [SamLewis0602/MMM-Traffic#60]
Hello ! 

First I would like to thank you for this amazing module ! We use it every day with my wife and it is super handy.

I would like to know if it would be possible to display the address set for the current day. To be clearer, I have set a different address for each day of the week and I would like it to appear under "Home to work". 

Is it possible/easy to do that ?

Cheers !

**Comment by SamLewis0602** [comment]
Glad you like the module! This shouldn't be too hard to implement, I'll try to take a look at it this week. Thanks for the idea!

**Comment by crazyanageek** [comment]
That would be amazing ! Thank you so much !

**Comment by SamLewis0602** [comment]
I just committed a new version with two new options: `showAddress` and `showAddress` which will let you customize the way the address is displayed. It will be displayed underneath the route name as you requested. Give it a try and let me know what you think!

**Comment by crazyanageek** [comment]
This is amazing Sam !! Thank you so much! I will try as soon as I come back
from work. Cheers !

**Comment by crazyanageek** [comment]
Works like a charm ! Really perfect !! Thank you, thank you, thank you !!
Cheers
Jonathan

**Comment by crazyanageek** [comment]
Hello Sam,

Last question, I have setup a destination for Saturday and Sunday in your
module (because I have to work on weekends unfortunately) and it's not
displaying them (I wrote : sat_destination and sun_destination). Do you
know why ?
Cheers !
Jonathan

**Comment by SamLewis0602** [comment]
The code for specific destinations on specific days was contributed by another user and they didn't support saturdays and sundays. I just pushed another update that adds support for those days. Enjoy! 😃

**Comment by crazyanageek** [comment]
Hello Sam,

You are a true master !! Thank you so much. Buy any chance do you have a
tipeee account or any account somewhere I could tip you to truly thank you?
Cheers.

Jonathan

**Comment by SamLewis0602** [comment]
Of course not! This was a fun project for me just before I finished my undergraduate degree and I'm happy to support it moving forward. Now that I work full time I don't have as much time to contribute but the changes you requested weren't too complex to implement. As long as you enjoy the module that's all the thanks I need! 😁

**Comment by crazyanageek** [comment]
Your very kind ! If one day you travel to Switzerland, let me know and I
will give you a tour !
Cheers.
Jonathan

**Comment by SamLewis0602** [comment]
Sounds great to me!

**Comment by SamLewis0602** [comment]
Hey Jonathan, I just fixed a bug with sun_destination so you'll want to update to make sure it works correctly. I also added in day-specific route names, in case you'd rather use that instead of the address to show which route you're seeing.

**Comment by crazyanageek** [comment]
Hi Sam, perfect ! I will try the patch when I get back home ! Cheers!

Jonathan

**Comment by crazyanageek** [comment]
Everything works really well now !! It's really good to be able to give a
"route name".
Cheers !!

Jonathan

2018-03-26 12:32 GMT+02:00 This is AO <kiwikiblue@gmail.com>:

> Hi Sam, perfect ! I will try the patch when I get back home ! Cheers!
>
> Jonathan
>
