### ISSUE TITLE
Current Commute remains blank

### ISSUE THREAD

**Issue by martincastillo3** [SamLewis0602/MMM-Traffic#61]
Hello, first thanks for the module, its very well explained, has lots of customization options, and they are very well listed. 

I have an issue with the module though, and I dont know where the problem is. I installed the module and got no error, then I copied the module in the config file, edited it with the API that got from google, added the adresses I wanted and I ran MM. The module seems to work as it appears on the screen, but only displays "Leave by --" or "Current Commute --" depending on wether i chose to put an arrival time or not. Then I tried it with the default adresses and the same happens.

 This is a screenshot of what it displays.
![traffic module](https://user-images.githubusercontent.com/37523525/37575692-4d69fe10-2b07-11e8-9521-66070dec01d0.jpg)

I then tried with another API key, and none key, and the same happens, so I imagine it has something to do with that. 

Is there any info I can provide so you can tell me if its the API or something else? or is there something in particular I have to do when requesting the key? 
Thank you very much! looking forward to solve this issue and enjoy your module!

**Comment by SamLewis0602** [comment]
Hi Martin, I'm glad you enjoy the module! This behavior (the dashes) can appear based on what you have in your config for the following 4 options:
showWeekend
allTime
startHr
endHr

These allow you to set certain times that the module will operate during the day, and outside of those times you will see the dashes. showWeekend will disable the module during the weekend if set to false, which will then cause it to show the dashes instead. 

If you don't set any of these, then the module will operate 24/7 by default. Check your config to see if these options are set.

**Comment by martincastillo3** [comment]
Thanks for the quick response! I turned on my raspberry and opened MagicMirror and without changing anything now displays time of travel, red color for traffic and road to use, so I think the configuration was set not to operate on weekends as I installed it yesterday (Sunday). It works great, thanks for the help!

**Comment by SamLewis0602** [comment]
That's most likely what it was. My pleasure!
