### ISSUE TITLE
arrival times for different destinations

### ISSUE THREAD

**Issue by rachnov55** [SamLewis0602/MMM-Traffic#62]
is it possible to have different arrival times for different destinations either for same or different day?

eg.  

Destination B, arrival time 1500
Destination C, arrival 1700

I've tried adding arrival_time after each destination, but it calculates everything based on the last arrival time provided

**Comment by SamLewis0602** [comment]
Do you mean options like mon_arrival_time for each day of the week?

**Comment by SamLewis0602** [comment]
I assume that is what you meant :D so I went ahead and added mon_arrival_time, etc. for each day of the week. Run `git pull` in your MMM-Traffic directory to get the latest version! Be aware, I made significant changes to how the routeName line works, see #63 for explanation.
