### ISSUE TITLE
showRouteInfo and routeName are not displaying

### ISSUE THREAD

**Issue by AndrewMcClelland** [SamLewis0602/MMM-Traffic#67]
First off, great module! Seems to work great other than a slight quirk I have with the showRouteInfo and routeName not displaying... (may likely be an error on my part).

The "Leave by TIME" works well and is coloured green for a no-traffic commute. But the route info and route name are not displayed (only the car symbol and the "Leave by TIME" are displayed).

Here is my current code:
`{` \
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`module: 'MMM-Traffic',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`position: 'top_left',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`config: {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`api_key: 'WORKING API KEY',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`origin: 'WORKING ADDRESS',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`destination: 'WORKING ADDRESS',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`arrival_time: '0930',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`mode: 'driving',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`showrouteInfo: true,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`route_name: 'Home to Work',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`changeColor: true,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`showWeekend: false,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`allTime: true,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`hideOffHours: true`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`}`
`}`

Any ideas??

**Comment by SamLewis0602** [comment]
Looks like you just need to capitalize the 'R' in showRouteInfo :D

**Comment by AndrewMcClelland** [comment]
Oh... well that's embarrassing! I guess the late night MMM configuring got to me.

Thanks for the quick response and the great module! Keep it up!

**Comment by SamLewis0602** [comment]
No worries, it happens to the best of us! 😃  my pleasure!
