### ISSUE TITLE
Loading commute

### ISSUE THREAD

**Issue by ReD1470** [SamLewis0602/MMM-Traffic#70]
Hey there!

How hard can it be right. you have done alle the hard work work for me.... but i cannot seem te get it to work :-(
i managed to get an API from google and inserted it in to the module. but no go. below is my module part. maybe you can tell me whts wrong here
tnx, and greets from holland!
ps if needs be i can let you know the api key

module: "MMM-Traffic",
		position: "top_left",
		classes: "dimmed medium", //optional, default is "bright medium", only applies to commute info not route_name
		config: {
			api_key: "xxxx",
			mode: "driving",
			origin: "Icarusblauwtje 14 Breda",
			destination: "Stökskesweg 9 Bergeijk",
			//mon_destination: "116th St & Broadway, New York, NY 10027",
			//fri_destination: "1 E 161st St, Bronx, NY 10451",
			arrival_time: "0830", //optional, but needs to be in 24 hour time if used.
			route_name: "Home to Work",
			changeColor: true,
			showGreen: false,
			limitYellow: 5, //Greater than 5% of journey time due to traffic
			limitRed: 20, //Greater than 20% of journey time due to traffic
			traffic_model: "pessimistic",
			interval: 120000 //2 minutes

**Comment by SamLewis0602** [comment]
No need for the API key! You should always keep those private to make sure nobody abuses the key and google then thinks it's you. You may have just left this out of your post, but do you have a closing curly bracket for your config object? It has to end with a '}'

**Comment by ReD1470** [comment]
also, below is the error i can dig up using pm2 log mm
|mm       |     at Request.emit (events.js:211:7)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1083:12)
0|mm       |     at Object.onceWrapper (events.js:313:30)
0|mm       |     at emitNone (events.js:111:20)
0|mm       | TypeError: Cannot read property 'legs' of undefined
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_helper.js:56:57)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:185:22)
0|mm       |     at emitTwo (events.js:126:13)
0|mm       |     at Request.emit (events.js:214:7)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1161:10)
0|mm       |     at emitOne (events.js:116:13)
0|mm       |     at Request.emit (events.js:211:7)
0|mm       |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:1083:12)
0|mm       |     at Object.onceWrapper (events.js:313:30)
0|mm       |     at emitNone (events.js:111:20)

**Comment by SamLewis0602** [comment]
So that likely points to something wrong with your API key. See my comment in #16 for a URL you can use to test your api key.

**Comment by ReD1470** [comment]
hey! tnx for such a fast reply!
- closing bracket - check! it is there
- #16, tried the url and got the forllowing
{
   "error_message" : "You have exceeded your daily request quota for this API. If you did not set a custom daily request quota, verify your project has an active billing account: http://g.co/dev/maps-no-account",
   "routes" : [],
   "status" : "OVER_QUERY_LIMIT"
}

I have created the api using defaults, so have i have not set a quota
and will look into that, hopefully I do NOT have to actually start paying as this was not my intention ;-)
Just like a weather api i'am hoping on a free API upto X logons a day

i' ll let you know how it goes
Tnx again

**Comment by SamLewis0602** [comment]
Google very recently changed their billing structure for the Maps API. They still offer up to $200 of usage per month for free. For use on a personal smart mirror, you should never reach this number, but they may require an active billing account on file so that they are able to charge if you go over.

**Comment by SamLewis0602** [comment]
Please come back and let me know what resolves the issue, so that others can find this thread later and solve their problem as well. Thanks!

**Comment by ReD1470** [comment]
got a google account,  got a new API
tested the api using the url  from google, and got directions
added the module, but it blocks all other modules unless i place it last in the config file
no log errors when i start pm2 log mm
but nothing on the screen either
0|mm       | Connecting socket for: MMM-Traffic
0|mm       | MMM-Traffic helper started ...
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.

your  guess is better than mine!

**Comment by SamLewis0602** [comment]
If there aren't any errors then it's hard for me to diagnose. Do you see "Loading..." or does it not show up at all?

**Comment by ReD1470** [comment]
yeah no errors makes it difficult. but indeed. like i said. pm2 log mm show no errors, and on the display we get nog information. but like I said, I do have to move the module to the end of the config or other modules do not start
- any other means of showing logs?
- i have tried another traffic modules and that one works. forgot the name, wille dig it up asap and let you know
- maybe an idea to put only your module in the config, to avoid typos or other stuff?

**Comment by ReD1470** [comment]
when i use the module MMM-MyCommute, then the api works. ive attached some screens to (maybe) clarify the situation.
![screen-my-commute](https://user-images.githubusercontent.com/42188645/44421665-84ab8e80-a581-11e8-90f4-8e08b7f7943f.PNG)
![screen-traffic](https://user-images.githubusercontent.com/42188645/44421666-84ab8e80-a581-11e8-85c0-22475db668c7.PNG)
![screen-traffic-log](https://user-images.githubusercontent.com/42188645/44422100-917cb200-a582-11e8-988f-a4a7e6a7f654.PNG)


even tried with a clean config, with only the traffic module in it, no go
!?? could the be a language issue?? nl, and metric?
just grasping straws here

**Comment by ReD1470** [comment]
…. do you have a picture what the end result should look like?
i may have it running.. 
![screen-traffic-working](https://user-images.githubusercontent.com/42188645/44423327-23d28500-a586-11e8-9957-117433cadfa5.PNG)

**Comment by SamLewis0602** [comment]
Yes, that is how it should look. That is how it looks when you have the arrival_time configured.

**Comment by SamLewis0602** [comment]
Glad you were able to figure it out. What did you change?

**Comment by ReD1470** [comment]
went back to clean config, pasted the module, changed nothing. not event API key. and it stated loading commute
then changed the api, tried again, a voila. change address and time etc. still working.
baffled but hey THANKS 4 da support!
ps route_name value should show up as wel??

**Comment by SamLewis0602** [comment]
Sorry for the delay. I'm glad it works, it must've just been a typo somewhere in the config, those can be hard to spot. Glad it's working! I'll close this issue.
