### ISSUE TITLE
No commute time

### ISSUE THREAD

**Issue by LeyDi1987** [SamLewis0602/MMM-Traffic#72]
Hi,

Eveything works, accept no 'prepend text is showing. Loadingtext is doing well.
How can I make it work?
This are my config

    defaults: {
        api_key: 'used my api Key',
        mode: 'driving',
        interval: 300000, //all modules use milliseconds
        origin: 'Rotterdam, Nederland',
        destination: 'Maastricht, Nederland',
        traffic_model: 'best_guess',
        departure_time: 'now',
        arrival_time: '1400',
        loadingText: 'Reistijd laden...',
        prependText: 'Huidige reistijd',
        changeColor: true,
        showRouteInfo: true,
        showRouteInfoText: '{routeName} via {summary}, aankomsttijd om {arrivalTime}',
        limitYellow: 10,
        limitRed: 30,
        showGreen: true,
        language: config.language,
        show_summary: true,
        showWeekend: true,
        allTime: true,
        startHr: 0,
        endHr: 23,
	      leaveByText:' vertrek om',
        hideOffHours: false,
        showAddress: true,
        showAddressText: 'Van {origin}<br>Naar {destination}'
    },

**Comment by SamLewis0602** [comment]
leaveByText will be used instead of prependText because you have the arrival_time parameter set. I see you have that set as well, so let me know if you're not seeing that text appear.

**Comment by LeyDi1987** [comment]
it works now thanks!
