### ISSUE TITLE
Stuck on loading commute...

### ISSUE THREAD

**Issue by anthony6608** [SamLewis0602/MMM-Traffic#73]
Hi! Thank you so much for making this module. It will definitely add to my MM once I am able to figure this out.

I am stuck on Loading commute and it isn't display anything. I have used the URL with my API key and I get results, so I know its not on google's end. For some reason it doesnt seem like the Rpi is hitting google's servers.

Could you help me figure out whats going on? Thanks!

**Comment by SamLewis0602** [comment]
Could you post your config for the module? Don't forget to remove your API key and any sensitive addresses before posting here.

**Comment by SamLewis0602** [comment]
Also, do you have any non-US characters in your address?

**Comment by Burner911** [comment]
I also have a similar issue. Here is my config:

```javascript
module: 'MMM-Traffic',
    position: 'top_left',
	classes: 'dimmed medium', //optional, default is 'bright medium', only applies to commute info not route_name
	config: {
		api_key: '######',
		mode: 'driving',
		origin: '#####',
		destination: '#####',
		arrival_time: '', //optional, but needs to be in 24 hour time if used.
		route_name: 'Home to Work',
		changeColor: true,
		showGreen: false,
		limitYellow: 5, //Greater than 5% of journey time due to traffic
		limitRed: 20, //Greater than 20% of journey time due to traffic
		traffic_model: 'pessimistic',
		interval: 120000, //2 minutes
		showRouteInfo: true
```

**Comment by Akkor70** [comment]
Same problem here

**Comment by a-i-ks** [comment]
I have the same problem. Here is my config. It doesn't work with my self-defined address, nor with the address from the example config. 
```javascript
{
	module: 'MMM-Traffic',
	position: 'middle_center',
	classes: 'dimmed medium', //optional, default is 'bright medium', only applies to commute info not route_name
	config: {
		api_key: '#####',
		mode: 'driving',
		//origin: 'My home address. Copied from Google Maps search input field',
		origin: '4 Pennsylvania Plaza, New York, NY 10001',
		destination: '1 MetLife Stadium Dr, East Rutherford, NJ 07073',
		//destination: 'some coordinates',
		arrival_time: '0845', //optional, but needs to be in 24 hour time if used.
		route_name: 'Arbeitsweg',
		changeColor: true,
		limitYellow: 5, //Greater than 5% of journey time due to traffic
		limitRed: 20, //Greater than 20% of journey time due to traffic
		interval: 120000, //2 minutes,
		allTime: false,
		startHr: 13,
		endHr: 14,
		hideOffHours: true
	}
}
```
Is there a possibility to enable a debug log?

**Comment by SamLewis0602** [comment]
You can open the console in your browser to check for client-side errors, and use `pm2 logs mm` if you use pm2 to run the server on your Pi. If not, use `node` commands to see the server side logs.

**Comment by a-i-ks** [comment]
The browser console does not show any errors. 
On this system I start the MagicMirror module with the command "npm start". The output is printed directly to the console. Also there are no errors to see. 
Perhaps it's because I'm behind a company proxy? However, the newsfeed module can load the newsfeed without any problems.  
I have a similar configuration at home where I use pm2 and no proxy. I will test it again this evening.

**Comment by SamLewis0602** [comment]
It shouldn't be related to the proxy as long as your company is not blocking Google maps. I just pushed an update that will log a message to your terminal if the API is returning an error. Give it a try and see if you see any messages in your terminal now.

**Comment by a-i-ks** [comment]
Thank you very much for your quick help. I pulled your update. When re-running "npm install" in the MMM-Traffic folder I noticed that I still had a faulty proxy configuration for the npm install command.  I was able to fix this problem. 
After restarting MagicMirror I have the following log output.
(I now actually believe that the problem is caused by the proxy, which maybe sends an HTML error page back to the GET request. I'll try again later at home. Thanks for the help until here.) 
```
osboxes@osboxes:~/MagicMirror$ npm start

> magicmirror@2.6.0 start /home/osboxes/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-Traffic
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-Traffic
MMM-Traffic helper started ...
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
Whoops! There was an uncaught exception...
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/osboxes/MagicMirror/modules/MMM-Traffic/node_helper.js:62:18)
    at self.callback (/home/osboxes/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/osboxes/MagicMirror/modules/MMM-Traffic/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.onError (/home/osboxes/MagicMirror/modules/MMM-Traffic/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:315:30)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

**Comment by SamLewis0602** [comment]
Ah, yeah that does look right. Sounds good, let me know if you're able to get it working at home 👍

**Comment by a-i-ks** [comment]
As already suspected it runs without proxy without problems. 
@Akkor70 @Burner911 @anthony6608 You could try to recheck if the "npm install" command was executed successfully inside the "MMM-Traffic" modules directory and if you are behind a nasty proxy this might lead also to this error.

**Comment by SamLewis0602** [comment]
Great! Glad you could get it working. I'm going to close this for now since I haven't heard from the others in a while, anyone feel free to open a new issue if you are still having trouble.
