### ISSUE TITLE
Google Map Quota limit...

### ISSUE THREAD

**Issue by thymon13** [SamLewis0602/MMM-Traffic#75]
Hi all,

Now I have this message :

`Google Maps API-Call Quota reached for today -> no more calls until 0:00 PST`

how much to adjust the interval?
(sorry for my English)

Thanks in advance

**Comment by SamLewis0602** [comment]
I'm not sure exactly what Google's limits are, but you can check their website. If you can't find it, just increase the interval to every 2 minutes or so (depending on how many traffic modules you have using the same API key).

**Comment by thymon13** [comment]
it's here : https://developers.google.com/maps/documentation/javascript/usage-and-billing
