### ISSUE TITLE
Customizable Amber/Red Thresholds

### ISSUE THREAD

**Issue by CommanderB** [SamLewis0602/MMM-Traffic#8]
It would be great if the threshold triggers for amber and red were config parameters.

```javascript
limitAmber: 20,
limitRed: 50
```

and then 

```javascript
        //change color if desired and append
        if (this.config.changeColor) {
          if (this.trafficComparison >= 1 + (this.config.limitRed / 100)) {
            commuteInfo.className += ' red';
          } else if (this.trafficComparison >= 1 + (this.config.limitAmber / 100)) {
            commuteInfo.className += ' yellow';
          } else if (this.config.showGreen) {
            commuteInfo.className += ' green';
          }
        }
```

This should work... but my test commutes aren't tripping the colour change

**Comment by SamLewis0602** [comment]
Nice idea! Are you sure that the traffic conditions are currently bad enough to trip the color change? You can navigate to the API url constructed using `getParams()` in your browser to see the durations being returned. Also, I believe the `duration_in_traffic` parameter is only returned my the Google Maps API when the mode is set to driving.

**Comment by CommanderB** [comment]
I have dialed limitAmber down to 1 i.e. 1% and its not changing on a drive which is probably 10% longer than optimal...

But I will play with `getParams()` and see what I get. Thanks.

**Comment by SamLewis0602** [comment]
Once you get it working feel free to submit a pull request!

**Comment by SamLewis0602** [comment]
I'll double check that it is working on it's own.

**Comment by SamLewis0602** [comment]
Just checked, looks like there's a bug with `this.trafficComparison` always being 0 in `getDom`. Looking into it now.

**Comment by CommanderB** [comment]
Yeah - I don't get a `duration_in_traffic` returned via the constructed API url , but using regular maps I get a time now and a time without traffic

**Comment by SamLewis0602** [comment]
Looks like using `parseInt()` when setting `this.trafficComparison` in the socketNotificationReceived function wasn't working correctly. Not sure why, but I don't think it's necessary anyway. So that issue is now fixed. As far as your api call not returning a duration_in_traffic, I'm not sure why that would be.

**Comment by SamLewis0602** [comment]
Looks like it was because of this issue if you're curious: http://stackoverflow.com/questions/12318830/parseint08-returns-0

**Comment by CommanderB** [comment]
Got it working! Will submit pull request tomorrow.

**Comment by SamLewis0602** [comment]
Awesome! Thanks for helping catch that bug.

**Comment by SamLewis0602** [comment]
If you don't mind changing the config to `limitYellow` instead of `limitAmber ` I'd prefer that to keep it consistent throughout the module :D
