### ISSUE TITLE
Multiple Waypoints

### ISSUE THREAD

**Issue by JanMarcusEskes** [SamLewis0602/MMM-Traffic#80]
Hello,
I like the module very much and have installed it in my mirror for a few days now. Since I also have different destinations I find the function to define multiple destinations very good. Unfortunately I also have several intermediate stops on the track every day. Is there similar to the destination for each day also the possibility to define intermediate stops for each day individually?

**Comment by SamLewis0602** [comment]
@JanMarcusEskes I will have to look at the API and see how they expose stops, but I imagine it is possible. I am going to dig back into this project this weekend but will be focusing on bug fixes and error handling first, then updating documentation to simplify initial install, as well as general simplification to the code to make this module more supportable for me. If I have time, I will check out this feature. Sorry for the delayed response.

**Comment by SamLewis0602** [comment]
@JanMarcusEskes This is already supported using the `waypoints` option in the config. See the readme for details.
