### ISSUE TITLE
Best way

### ISSUE THREAD

**Issue by ArnoStrasbourg** [SamLewis0602/MMM-Traffic#82]
I would like to know if the module choose automatically the best way to reach a destination, please

**Comment by SamLewis0602** [comment]
It uses the Google Maps API so it uses whatever the default is if you were to enter the destination into the Google Maps App on a phone or their website.

**Comment by ArnoStrasbourg** [comment]
Ok, default in the app is the fastest way. I have not yet seen if it changes the route because the traffic is not yet as important as before the confinement ... fortunately !!

**_Enhancement_** : Maybe you could consider the possibility of choosing an option like the shortest or the fastest way or display 2 different routes.

In any case thank you for the job.
