### ISSUE TITLE
Time way off...

### ISSUE THREAD

**Issue by brommeltje** [SamLewis0602/MMM-Traffic#84]
Driving time seems way off since last update... 
This route gives me 617 minutes... And it should be around 61 minutes...
{
	module: "MMM-Traffic",
	position: "bottom_center",
	config: {
		accessToken: "****snip****",
		originCoords: "51.4821864,5.67775294",
		destinationCoords: "51.9846844,5.1052945",
		firstLine: "{duration} mins",
		secondLine: "Home > Office"
	}
},

**Comment by SamLewis0602** [comment]
Did you make sure to do longitude,latitude? Google Maps shows you latitude,longitude by default so you have to reverse it. Let me know!

**Comment by brommeltje** [comment]
That did the trick....

**Comment by SamLewis0602** [comment]
Just added a note in the README to clarify this. Thanks!
