### ISSUE TITLE
API Error - InvalidInput   Coordinate is invalid: -84.504259, 33.882107

### ISSUE THREAD

**Issue by RStadlmair** [SamLewis0602/MMM-Traffic#85]
Hi !
Just testing your new module.
Even with the coordinates of your sample i get this error when starting up MM.
Any ideas ?
R.

My Config:
	// MMM-Traffic
	{
		module: "MMM-Traffic",
		position: "upper_third",
		config: {
			accessToken: "pk.ey**********************4Q",
			originCoords: "-84.504259, 33.882107",
			destinationCoords: "-84.504259, 33.882107",
			debug: true
		}
	},

**Comment by SamLewis0602** [comment]
Hey, make sure you don't have a space after the comma in your coordinates. I'm going to leave this issue open to add automatic checking for that.

**Comment by RStadlmair** [comment]
Hi !
Removing the spaces and switching the coordinates as they come from google according to [this](url) hint did the trick - THANKS!
Please update the docs.
R.
