### ISSUE TITLE
Wrong Calculation

### ISSUE THREAD

**Issue by emrahaslan** [SamLewis0602/MMM-Traffic#87]
I confused about travel estimation compared koordinats with Google Map.
It looks different.

{
			module: "MMM-Traffic",
			position: "top_left",
			config: {
				accessToken: "my token",
				originCoords: "29.19571408770105,40.91254600000002",
				destinationCoords: "29.432513571372965,40.78107263003665",
				firstLine: "{duration} dakika",
				secondLine: "Tubitak Gebze Serbest Bölge",
			}
		},
		{
			module: "MMM-Traffic",
			position: "top_left",
			config: {
				accessToken: "my token",
				originCoords: "29.19734100000005,40.91254600000002",
				destinationCoords: "29.015470999999934,41.066401999999925",
				firstLine: "{duration} dakika",
				secondLine: "Zorlu Center AVM"
			}
		},

The Result is :
![image](https://user-images.githubusercontent.com/54321532/92907728-3f8b7b00-f42e-11ea-931f-8f658a308599.png)

But when I Enter these coordinates over Google Map It shows correct minutes (for second one)

![image](https://user-images.githubusercontent.com/54321532/92908215-b0cb2e00-f42e-11ea-9abd-b2295bf7aa4c.png)

**Comment by emrahaslan** [comment]
For second location mapbox api shows 11 Minutes.
But the correct time is google one.

Is this related with API or module ? Please help me

**Comment by emrahaslan** [comment]
Sorry I mixed coordinates orders. When I swap lat-long it works.

**Comment by SamLewis0602** [comment]
No worries, glad you got it worked out! 😄
