### ISSUE TITLE
Feature request: commuting option bases on day time

### ISSUE THREAD

**Issue by lavolp3** [SamLewis0602/MMM-Traffic#90]
(As discussed on the forum):
MMM-MyCommute already works with config options for time frames (startTime and endTime) for every destination.
That way you can have the module calculate your commuting time (and way) depending of the time of day. In the morning to work/school) in the afternoon back home.
Should be easily implementable also here by making checks with moment which time frame you are in.

**Comment by SamLewis0602** [comment]
This can be done already, by just adding two MMM-Traffic modules to your config and using the startHours and endHours as seen in the documentation here:

https://github.com/SamLewis0602/MMM-Traffic#per-daytime-customization

Let me know if there's something you can't accomplish with these options.
