### ISSUE TITLE
MMM-Traffic doesn‘t show with page module

### ISSUE THREAD

**Issue by kusselin** [SamLewis0602/MMM-Traffic#94]
Hi, when i get the mmm-pages module your traffic module doesn‘t show on the M! Screen. Have you any idea?

**Comment by SamLewis0602** [comment]
See #86 for progress on this. If you pull the latest version of MMM-Traffic right now, it will work with pages, but when you first start up it will look like Traffic is stuck on the loading state. Just wait until the next update (5 minutes by default) and it will work after that. We are working to fix this problem in the other thread.
