### ISSUE TITLE
Font Size & Spacing

### ISSUE THREAD

**Issue by fmmcyyc** [SamLewis0602/MMM-Traffic#97]
Hi I am having a rough time to reduce the font size and line spacing for this module.  Any help would be appreciated..

**Comment by SamLewis0602** [comment]
Hi there, I haven't built in any ways to change those things. Is there a common way you do that in other modules or your mirror?

**Comment by fmmcyyc** [comment]
I usually add this within the custom.css file and it will work:
.newsfeed .medium {
      font-size: 16px;
      line-height: 16px;
  }

But it does not for your module.. So sorry to just dump all these issues on you. But I love this module.

**Comment by SamLewis0602** [comment]
@fmmcyyc More good news, custom styles are officially supported! Check out the styles section of the README to see the classes and an example. Let me know if you see any issues. Thanks for the suggestion!

https://github.com/SamLewis0602/MMM-Traffic#styling
