### ISSUE TITLE
Is bicycle / transit / walking possible with this module ?

### ISSUE THREAD

**Issue by maxencekyz** [SamLewis0602/MMM-Traffic#98]
Hello,

Module works perfectly but it always shows the driving time.
I would **like to see how long does it takes by walking, bicycling or transit**. Any issue to do this ?
I tried to put "mode" but it do not work. Always showing driving time. Here is my config :

> 	{
			module: "MMM-Traffic", 
			position: "bottom_left",
			config:
			{
				accessToken: "XXXX",
				originCoords: "3.240206,50.175264", 
				destinationCoords: "3.069385,50.636668", 
				mode: 'bicycling',
				firstLine: "{duration} mins",
		        secondLine: "Trajet Maison-Boulot vélo" 
			}
		},

Thanks per advance,
- Max

@sanjayankur31 @pvyParts @Dozer1170 @paviro

**Comment by sanjayankur31** [comment]
Sorry @maxencekyz , haven't used this in a long while so I don't quite know any more.

**Comment by SamLewis0602** [comment]
Hey @maxencekyz , this isn't currently in the module but let me look at the mapbox documentation and see if those methods are included in the API. If so, it should be a fairly easy addition

**Comment by SamLewis0602** [comment]
@maxencekyz The mapbox API does not support public transit, but I just added support to the module for walking and cycling. Check out the 'mode' option in the README and update your module to give it a try. Let me know if you run into any issues.

**Comment by maxencekyz** [comment]
Hello @SamLewis0602 ,

Thank you for your help.
Here is my config :

> 	{
			module: "MMM-Traffic",
			position: "bottom_left",
			config: {
				accessToken: "xxxxxx",
				originCoords: "3.240206,50.175264", 
				destinationCoords: "3.069385,50.636668", 
				mode: 'cycling', 
				firstLine: "{duration} mins",
		        secondLine: "Trajet Maison-Boulot vélo"
			}
		},

I tried as well   **mode: "cycling",**
It doesn't work. It still shows the driving time, not cycling.
Where do i'm wrong ?

Thanks per advance,

**Comment by maxencekyz** [comment]
My bad! You were right, i forgot to `git pull` ! It's working now, thank you so much !
Last question : Now that you've implemented cycling and walking mode.

In which file and what should I do, to implement icons for cycling and walking? Instead of the car logo.
![image](https://user-images.githubusercontent.com/80335419/111193370-62a00e80-85ba-11eb-9a60-76073deba279.png)

Thank you,

**Comment by SamLewis0602** [comment]
Ah good call. No need for you to do that, I will change the icon according to the mode. Let me get to that later today after work and I will tag you back here when it's ready for you to update! Thanks for the suggestion.

**Comment by SamLewis0602** [comment]
@maxencekyz Just added icons for cycling and walking. Run `git pull` again and you should see a different icon. Enjoy!

**Comment by maxencekyz** [comment]
That's amazing @SamLewis0602 ! Thanks for all the support you provide, everything works perfectly !!
Have a nic day and god bless you!!
