### ISSUE TITLE
Issues with MMM-Carousel

### ISSUE THREAD

**Issue by fmmcyyc** [SamLewis0602/MMM-Traffic#99]
Great module, but cannot display more than 1 instance with Carousel. Keeps displaying "Loading..."

**Comment by SamLewis0602** [comment]
@fmmcyyc Hey, just pushed an update to the module. Run `git pull` inside your `MMM-Traffic` directory to get the latest version, and test to see if it works with Carousel now. I expect that it will but I haven't had a chance to test it with Carousel specifically yet. Please let me know. Thanks.

**Comment by fmmcyyc** [comment]
Awesome. It works. Thanks a lot.. 
Just as an FYI. It only works within the "ignoreModules". Not within a slide, this works for me thought.
Thanks.

**Comment by SamLewis0602** [comment]
Thanks for the follow up. I'll leave this issue open and get Carousel set up on my laptop so I can test Traffic with it and try to figure out what's up. I'll tag you back here if I make any progress.

**Comment by SamLewis0602** [comment]
Hey @fmmcyyc , so sorry for the long delay. Good news, I just pushed another fix and this time I've confirmed that MMM-Carousel is working, even with the slides option. Enjoy and thanks for your patience!

**Comment by SamLewis0602** [comment]
Don't forget to run `git pull` inside the `MMM-Traffic` directory to get the latest version
